# Generated by Django 4.2.7 on 2025-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_approved_by_customuser_is_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
