# Generated by Django 4.2.7 on 2025-08-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_remove_cvsubmission_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
