# Generated by Django 4.2.7 on 2025-08-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_education_university_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
