# Generated by Django 4.2.7 on 2025-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_education_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalskill',
            name='multimedia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='network',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='operating_systems',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='web_development',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
