# Generated by Django 5.1 on 2025-09-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_technicalskill_multimedia_technicalskill_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='graduation_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='status_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
