# Generated by Django 5.1 on 2025-09-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_cvsubmission_country_cvsubmission_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvsubmission',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='cohort_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='is_published_to_cvbook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='is_uca_student',
            field=models.BooleanField(default=False),
        ),
    ]
