# Generated by Django 5.1 on 2025-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_cvsubmission_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accomplishment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.TextField(blank=True, default=''),
        ),
    ]
