# Generated by Django 4.2.7 on 2025-10-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_project_accomplishment_project_technologies_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='proficiency',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
