# Generated by Django 5.1 on 2025-10-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_language_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='presenting_organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='honors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='relevant_courses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reference',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
