# Generated by Django 4.2.7 on 2025-12-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
