# Generated by Django 4.2.7 on 2025-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_alter_reference_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
